# Generated by Django 3.2.9 on 2021-12-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65, unique=True, verbose_name='User name')),
                ('gender', models.CharField(max_length=65, verbose_name='User gender')),
            ],
        ),
    ]
